### ISSUE TITLE
requirements windows unclear

### ISSUE THREAD

**Issue by 0T0K0-Tensh1** [YuliangXiu/ECON#25]
the last 3 lines of the file look like this. i copied exactly. you tell me what is wrong
```
open3d
tinyobjloader==2.0.0rc7
git+https://github.com/facebookresearch/pytorch3d.git
git+https://github.com
```
please respect windows users.

**Comment by carlosedubarreto** [comment]
It doesnt seem like lack of respect, but just a person that is busy and also respect windows users so much that he tried to make something that windows users could install it.

So much that there is also information on the page detailing how to install on windows, and some issues talking about the steps you need to install on windows.

And just to give one example, its highly probablr that even if the last line was not incomplete you would not be able to install everything, simply because pytorch3d is a pain to build on windows (unless you follow specific direction that you have on the information that is also available on this repository)

I understand that you can get mad because the information is incomplete,m but in no way it means that its lack of respect.

**Comment by YuliangXiu** [comment]
> the last 3 lines of the file look like this. i copied exactly. you tell me what is wrong
> 
> ```
> open3d
> tinyobjloader==2.0.0rc7
> git+https://github.com/facebookresearch/pytorch3d.git
> git+https://github.com
> ```
> 
> please respect windows users.

_"You tell me what is wrong"_ --- WTF, what's wrong with you? 

Please respect the open-source contributors who share their experience selflessly!
