### ISSUE TITLE
How do I save the SMPLX UV Map?

### ISSUE THREAD

**Issue by raincrash** [YuliangXiu/ECON#54]
Great work on ECON! Is there a way to store the UVs in SMPLx UV map format?

**Comment by YuliangXiu** [comment]
You could register ECON's reconstruction with underneath SMPL-X to get the vertex-correspondence, which could be used to compute UV map. However, since the topology of ECON's output is relatively flexible, we use `xatlas` to compute character specific UV texture, see [avatarizer.py#L271](https://github.com/YuliangXiu/ECON/blob/master/apps/avatarizer.py#L271)

**Comment by YuliangXiu** [comment]
> Thanks for the quick reply @YuliangXiu. Are the ATLAS structures same as the one used by Densepose for example? [facebookresearch/DensePose#237](https://github.com/facebookresearch/DensePose/issues/237).

No.

**Comment by YuliangXiu** [comment]
@raincrash We recently released a new work, TeCH. Given a single image, TeCH could produce a **full textured avatar** with both intricate geometric details and consistent high-quality texture.

<div align="center">
    <video autoplay loop muted src="https://github.com/huangyangyi/TeCH/assets/7944350/f8fc55ed-9cbe-4b5f-bd1d-237396360713" type=video/mp4>
    </video>
  </div>

Homepage: https://huangyangyi.github.io/TeCH/
