### ISSUE TITLE
Can't save the results/outputs on Windows machine

### ISSUE THREAD

**Issue by justinjohn0306** [YuliangXiu/ECON#8]
![Capture](https://user-images.githubusercontent.com/34035011/210421052-55d75cb5-dad8-481c-9e13-59c60a912bb0.PNG)
I managed to get it working on Windows but it can't save the results for some reason. Ideas?

**Comment by YuliangXiu** [comment]
The output path filled with `\\` and '/' looks quite strange, the project is built on Ubuntu. Maybe you should update the output path with windows-compatible formats.

BTW, someone else has run ECON successfully under Windows, see [issues/7](https://github.com/YuliangXiu/ECON/issues/7).

**Comment by carlosedubarreto** [comment]
@justinjohn0306 in case you still ahve problems with it, just create the "examples" folder manually inside the png folder and run it again.

You might have a few other errors with different paths, create "examples" folder inside each one othe them and probably after executing it 3 or 4 times, it will run successfully.

**Comment by luwang03** [comment]
The problem is the path string is different for windows and ubuntu. In windows, the path string is linked by “\\”. So, you can add one line code "img_path = img_path.replace('\\','/')"  at line 146 (before code line "img_name = img_path.split("/")[-1].rsplit(".", 1)[0]") in file "./lib/dataset/TestDataset.py".
